import type { Visitor } from "./columns";

export const data: Visitor[] = [
    {
        id: "VIS-001",
        name: "Alice Johnson",
        email: "alice.j@innovate.com",
        company: "Innovate Inc.",
        host: "Bob Williams",
        purpose: "Project meeting",
        checkIn: "2024-07-29 09:05 AM",
        checkOut: "2024-07-29 05:00 PM",
        status: "Checked Out",
    },
    {
        id: "VIS-002",
        name: "Charlie Davis",
        email: "charlie.d@solutions.co",
        company: "Solutions Co.",
        host: "Diana Miller",
        purpose: "Sales demo",
        checkIn: "2024-07-29 09:30 AM",
        checkOut: "",
        status: "Checked In",
    },
    {
        id: "VIS-003",
        name: "Eve Smith",
        email: "eve.s@techforward.com",
        company: "Tech Forward",
        host: "Frank White",
        purpose: "Technical support",
        checkIn: "2024-07-29 10:00 AM",
        checkOut: "",
        status: "Checked In",
    },
    {
        id: "VIS-004",
        name: "George Brown",
        email: "george.b@datasys.com",
        company: "Data Systems",
        host: "Heidi Green",
        purpose: "Interview",
        checkIn: "2024-07-29 11:15 AM",
        checkOut: "2024-07-29 02:30 PM",
        status: "Checked Out",
    },
    {
        id: "VIS-005",
        name: "Ivy Black",
        email: "ivy.b@nextgen.com",
        company: "NextGen Solutions",
        host: "Jack Blue",
        purpose: "Partnership discussion",
        checkIn: "2024-07-30 09:00 AM",
        checkOut: "",
        status: "Expected",
    },
     {
        id: "VIS-006",
        name: "John Doe",
        email: "john.d@acme.com",
        company: "Acme Corp",
        host: "Jane Smith",
        purpose: "Quarterly review",
        checkIn: "2024-07-29 08:45 AM",
        checkOut: "2024-07-29 06:15 PM",
        status: "Checked Out",
    },
    {
        id: "VIS-007",
        name: "Peter Jones",
        email: "peter.j@globaltech.com",
        company: "Global Tech",
        host: "Susan Chen",
        purpose: "Client visit",
        checkIn: "2024-07-29 10:20 AM",
        checkOut: "",
        status: "Checked In",
    },
];
